// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdSDjRMem0ay7t2EFcf5T7W3NnQQI17Vg',
    appId: '1:339370215318:web:cc0b945d03c3feda1a7fb7',
    messagingSenderId: '339370215318',
    projectId: 'base-flutter-7b937',
    authDomain: 'base-flutter-7b937.firebaseapp.com',
    storageBucket: 'base-flutter-7b937.appspot.com',
    measurementId: 'G-CXCTV2YPNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoGHF-ZuGvgW1nmn2uoZVtnA66AfemdRc',
    appId: '1:339370215318:android:22b4009adb1c1e411a7fb7',
    messagingSenderId: '339370215318',
    projectId: 'base-flutter-7b937',
    storageBucket: 'base-flutter-7b937.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5gcdNf-wMzgT47FSGaY1HQjwtJICVVJ0',
    appId: '1:339370215318:ios:205a9428da46b96e1a7fb7',
    messagingSenderId: '339370215318',
    projectId: 'base-flutter-7b937',
    storageBucket: 'base-flutter-7b937.appspot.com',
    iosClientId: '339370215318-a3a92vh2epj6geo24nd4in41dnf0hgb1.apps.googleusercontent.com',
    iosBundleId: 'com.example.providerBase.dev',
  );
}
