// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0qjpLzKMCC_JpzI1LWTkGxPc1uzYfIJY',
    appId: '1:902313079720:web:b583aa1a67a6c61b53a39d',
    messagingSenderId: '902313079720',
    projectId: 'provider-base-dev',
    authDomain: 'provider-base-dev.firebaseapp.com',
    storageBucket: 'provider-base-dev.appspot.com',
    measurementId: 'G-P75LMBVL29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo6ievLc1W0YXKlW-sBBvvk8hVbSGAEvQ',
    appId: '1:902313079720:android:88b8491dc733bf7a53a39d',
    messagingSenderId: '902313079720',
    projectId: 'provider-base-dev',
    storageBucket: 'provider-base-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZSsGJLv7qBzaO-gTmMNX8TaOSMRDZ_e0',
    appId: '1:902313079720:ios:5587ac34bb50d7ad53a39d',
    messagingSenderId: '902313079720',
    projectId: 'provider-base-dev',
    storageBucket: 'provider-base-dev.appspot.com',
    iosClientId: '902313079720-e463tsvu81n82fs0ood7lj9tgpt6o6em.apps.googleusercontent.com',
    iosBundleId: 'com.example.providerBase.dev',
  );
}
