// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBANzyGA_W_5s46E9Kuj-wDVS2vHwQUXiU',
    appId: '1:906320537444:web:c725c3550a8cf654b0fc71',
    messagingSenderId: '906320537444',
    projectId: 'provider-base-stg',
    authDomain: 'provider-base-stg.firebaseapp.com',
    storageBucket: 'provider-base-stg.appspot.com',
    measurementId: 'G-MFTKH25YG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPAdQsjZSCis6CU2mf44Lqu90eCfnoZmk',
    appId: '1:906320537444:android:364b905c01d1b471b0fc71',
    messagingSenderId: '906320537444',
    projectId: 'provider-base-stg',
    storageBucket: 'provider-base-stg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQRd9JUcLaaa9mGCABSnFGGLCmCozhevQ',
    appId: '1:906320537444:ios:756dfe57bc2c80e9b0fc71',
    messagingSenderId: '906320537444',
    projectId: 'provider-base-stg',
    storageBucket: 'provider-base-stg.appspot.com',
    iosClientId: '906320537444-f054drkv4hahn3tep4ks1jbbeg7uac3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.providerBase.stg',
  );
}
